### ISSUE TITLE
 Not found when using http.StripPrefix

### ISSUE THREAD

**Issue by phamtai97** [namely/docker-protoc#129]
Hi.
I created the api as follows:

```protobuf
service ServiceA {
  rpc Ping (service.common.proto.MessagePing) returns (service.common.proto.MessagePong) {
    option (google.api.http) = {
      get: "/core/serviceA/ping/{timestamp}"
    };
  }
}
```
Then, I configed file config.yaml

```yaml
backend: "localhost:8000"
cors:
  allow-origin: "*"
  allow-credentials: 
  allow-methods: "POST, GET, OPTIONS, PUT, DELETE"
  allow-headers: "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization"
proxy:
  port: 9000
  api-prefix: "/core"
swagger:
  file: "..swagger.json"
```
When I test API `http://localhost:9000/core/serviceA/ping/900000` by postman, the returned result is Not found.

I tried modifying the code in one place:
```go
//mux.Handle(prefix, handlers.CustomLoggingHandler(os.Stdout, http.StripPrefix(prefix[:len(prefix)-1], addRespHeaders(cfg, gwmux)), formatter))

mux.Handle(prefix, addRespHeaders(cfg, gwmux))
```
And API call result was successful.
I do not know the cause of the error that the line of code generated. Can you explain help me?
